package com.echo.feature.settings.viewmodel

import android.content.Context
import android.content.pm.PackageInfo
import com.echo.core.data.repository.CoreInventory
import com.echo.core.domain.model.EmulatorProfile
import com.echo.core.domain.model.IntentType
import com.echo.core.domain.model.LaunchTemplate
import com.echo.feature.launcher.EmulatorProfileRepository
import io.mockk.coEvery
import io.mockk.coVerify
import io.mockk.every
import io.mockk.mockk
import io.mockk.slot
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.ExperimentalCoroutinesApi
import kotlinx.coroutines.flow.flowOf
import kotlinx.coroutines.test.StandardTestDispatcher
import kotlinx.coroutines.test.advanceUntilIdle
import kotlinx.coroutines.test.resetMain
import kotlinx.coroutines.test.runTest
import kotlinx.coroutines.test.setMain
import org.junit.After
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertTrue
import org.junit.Before
import org.junit.Test

@OptIn(ExperimentalCoroutinesApi::class)
class EmulatorProfileEditorSaveTest {
    private val dispatcher = StandardTestDispatcher()

    private val detected = EmulatorProfile(
        id                   = "auto_vita3k",
        name                 = "Vita3K",
        packageName          = "org.vita3k.emulator",
        activityClass        = "org.vita3k.emulator.Emulator",
        intentType           = IntentType.COMPONENT,
        supportedPlatformIds = listOf("psvita", "psp"),
        intentArrayExtras    = mapOf("AppStartParameters" to listOf("-r", LaunchTemplate.TITLE_ID)),
        attachRomData        = true,
        coreMap              = mapOf("psvita" to "vita_core.so", "psp" to "ppsspp_core.so"),
        minVersionCode       = 42,
        isCustom             = false,
        isAutoGenerated      = true,
        autoSource           = "known-catalog",
    )

    private val repository = mockk<EmulatorProfileRepository>(relaxed = true) {
        every { profiles } returns flowOf(listOf(detected))
        every { getInstalledProfiles() } returns listOf(detected)
    }
    private val retroArchSetup = mockk<RetroArchSetup>(relaxed = true) {
        coEvery { inventory() } returns CoreInventory.Unlinked
    }

    private val context = mockk<Context>(relaxed = true) {
        every { packageManager.getInstalledPackages(0) } returns
            listOf(mockk<PackageInfo>().apply { packageName = "app.gamenative" })
    }

    @Before fun setUp() { Dispatchers.setMain(dispatcher) }
    @After fun tearDown() { Dispatchers.resetMain() }

    private fun buildVm() = EmulatorsSettingsViewModel(
        repository, mockk(relaxed = true), mockk(relaxed = true), mockk(relaxed = true),
        retroArchSetup, context,
    )

    @Test fun `renaming a detected profile must not strip its launch arguments`() {
        val saved = runSave { updateEditorName("My Vita") }

        assertEquals("My Vita", saved.name)
        assertEquals(detected.intentArrayExtras, saved.intentArrayExtras)
        assertTrue(saved.attachRomData)
        assertEquals(42, saved.minVersionCode)
        assertEquals(detected.coreMap, saved.coreMap)
        assertFalse(saved.isCustom)
        assertTrue(saved.userModified)
    }

    @Test fun `editing the core text replaces the per-platform cores`() {
        val saved = runSave { updateEditorCore("new_core.so") }

        assertEquals(mapOf("psvita" to "new_core.so", "psp" to "new_core.so"), saved.coreMap)
        assertEquals(detected.intentArrayExtras, saved.intentArrayExtras)
    }

    private fun runSave(edit: EmulatorsSettingsViewModel.() -> Unit): EmulatorProfile {
        val saved = slot<EmulatorProfile>()
        runTest(dispatcher) {
            val vm = buildVm()
            eventually("the runtime scan settles") { vm.uiState.value.pcRuntimes.isNotEmpty() }
            vm.openEditor(detected.id)
            vm.edit()
            vm.saveEditorProfile()
            advanceUntilIdle()
            coVerify { repository.savePersistedProfile(capture(saved)) }
        }
        return saved.captured
    }
}
